- name: Remove all axiomledger-nodes on target machines
  hosts: chaos_test
  ignore_unreachable: true
  tasks:
    - name: "Execute remove on the target machine"
      shell:
        cmd: |
          rm -rf node[0-9]*
        chdir: ~/ansible/nodes/
      register: result

    - name: Display result
      debug:
        var: result
