- name: Start four axiomledger-nodes on target machine (node1-node4)
  hosts: chaos-test[0] # ip : 172.16.30.81
  tasks:
    - name: "Copy nodes config to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/16_nodes_cluster"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          bash control_nodes.sh start 1 4
        chdir: ~/ansible/16_nodes_cluster
      register: result

    - name: Display result
      debug:
        var: result
###########################################################################################################
