- name: Start four axiomledger-nodes on target machine (node1)
  hosts: test1
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/control_cluster2.sh"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          bash control_cluster2.sh start 1 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result

######################################################################################################

- name: Start four axiomledger-nodes on target machine (node2)
  hosts: test2
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/control_cluster2.sh"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          bash control_cluster2.sh start 2 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result

######################################################################################################

- name: Start four axiomledger-nodes on target machine (node3)
  hosts: test3
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/control_cluster2.sh"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          bash control_cluster2.sh start 3 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result

###################################################################################################

- name: Start four axiomledger-nodes on target machine (node4)
  hosts: test4
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/control_cluster2.sh"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          bash control_cluster2.sh start 4 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
