- name: start node1
  hosts: test1
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh start 1 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
- name: start node2
  hosts: test2
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh start 2 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
- name: start node3
  hosts: test3
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh start 3 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
- name: start node4
  hosts: test4
  vars:
    network1: 172.16.13.132
    network2: 172.16.13.132
    network3: 172.16.13.132
    network4: 172.16.13.132
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh start 4 {{ network1 }} {{ network2 }} {{ network3 }} {{ network4 }}
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result