- name: node1 stop
  hosts: test1
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh stop 1
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
- name: node2 stop
  hosts: test2
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh stop 2
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
- name: node3 stop
  hosts: test3
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh stop 3
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
- name: node4 stop
  hosts: test4
  tasks:
    - name: "复制启动脚本到目标服务器上"
      copy:
        src: "{{ item }}" #文件或文件夹
        dest: "~/ansible/" #文件夹
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "files/control_cluster2.sh"

    - name: "在服务器上执行脚本"
      shell:
        cmd: |
          bash control_cluster2.sh stop 4
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
