- name: Execute a shell command example
  hosts: test1
  tasks:
    - name: Run shell command
      shell: ls -l ~/
      register: result

    - name: Display result
      debug:
        var: result
