- name: Check axiom process
  hosts: test1
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "./files/check_process.sh" # file or folder
        dest: "~/ansible/" #folder, repeated uploads will be overwritten by default
        owner: hyperchain
        group: hyperchain
        mode: 755

    - name: "Execute the script on the target machine"
      shell: bash ~/ansible/check_process.sh
    #  register: result

    #- name: Display result
    #  debug:
    #    var: result
