- name: Start chaosTest on one target machine
  hosts: chaos_test
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/chaos_test_scripts/network_loss/network_loss_ens3.sh"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          rm -rf ~/ansible/networkLossTest.log
          nohup bash network_loss_ens3.sh -n 5 -p 4001-4016 -c 90 > networkLossTest.log 2>&1 &
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
