- name: Start solo axiomledger node on target machine
  hosts: test1
  tasks:
    - name: "Copy the script to the target machine"
      copy:
        src: "{{ item }}"
        dest: "~/ansible/"
        owner: hyperchain
        group: hyperchain
        mode: 777
      with_items:
        - "../files/x.sh"
        - "../files/control_solo.sh"

    - name: "Execute the script on the target machine"
      shell:
        cmd: |
          bash control_solo.sh start
        chdir: ~/ansible
      register: result

    - name: Display result
      debug:
        var: result
